name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install NPM packages (use Yarn)
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Build
        run: yarn run build
        working-directory: ./frontend
        env:
          NODE_ENV: production

      - name: Copy directory to dist
        run: rsync -avz --exclude=".git" --exclude="node_modules" . ./dist/

      - name: Deploy to dist branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          MESSAGE: "{sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
